language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project drupal/recommended-project:^8.9 test-bloom --no-interaction
  - cd test-bloom
  - composer config repositories.chirripo path $TRAVIS_BUILD_DIR
  - composer config extra.enable-patching true
  - composer require drush/drush
before_script:
  - cd ~/test-bloom
  - composer require manaticr/bloom:"*"
  - ./vendor/bin/drush si bloom -y --db-url=sqlite://tmp/.ht.sqlite
